[package]
name = "notes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.0"
chrono = "0.4.19"
thiserror = "1.0.15"
dirs = "1.0.4"
gflags = "0.3"
